kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
  namespace: monitoring
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-web-config-file
  namespace: monitoring
data:
  web.yml: |-
    basic_auth_users: 
      admin: $2a$12$FJecO5oX25KfGiSpG0UYBuZikupMtEeOxb1f2Yu2rKzRBOuF6l6TW
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-k8s-rulefiles-0
  namespace: monitoring
  labels:
    prometheus-name: k8s
data:
  monitoring-prometheus-k8s-rules.yaml: ""
---
kind: Secret
apiVersion: v1
metadata:
  name: prometheus-k8s-tls-assets
  namespace: monitoring
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus-k8s
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      prometheus: k8s
  template:
    metadata:
      labels:
        app: prometheus
        prometheus: k8s
    spec:
      volumes:
        - name: tls-assets
          secret:
            secretName: prometheus-k8s-tls-assets
            defaultMode: 420
        - name: config-out
          emptyDir: {}
        - name: prometheus-k8s-rulefiles-0
          configMap:
            name: prometheus-k8s-rulefiles-0
            defaultMode: 420
        - name: configmap-prometheus-web-config-file
          configMap:
            name: prometheus-web-config-file
            defaultMode: 420
        - name: prometheus-k8s-db
          emptyDir: {}
      containers:
        - name: prometheus
          image: 'quay.io/prometheus/prometheus:v2.31.1'
          args:
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=24h'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.no-lockfile'
            - '--web.route-prefix=/'
            - >-
              --web.config.file=/etc/prometheus/configmaps/prometheus-web-config-file/web.yml
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config-out
              readOnly: true
              mountPath: /etc/prometheus/config_out
            - name: tls-assets
              readOnly: true
              mountPath: /etc/prometheus/certs
            - name: prometheus-k8s-db
              mountPath: /prometheus
            - name: prometheus-k8s-rulefiles-0
              mountPath: /etc/prometheus/rules/prometheus-k8s-rulefiles-0
            - name: configmap-prometheus-web-config-file
              readOnly: true
              mountPath: /etc/prometheus/configmaps/prometheus-web-config-file
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46USZmdFk4Vjc=
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46USZmdFk4Vjc=
      restartPolicy: Always
      serviceAccountName: prometheus-k8s
      serviceAccount: prometheus-k8s

